### ISSUE TITLE
Modules with own import() not supported?

### ISSUE THREAD

**Issue by jo-37** [tobyink/p5-exporter-tiny#4]
Maybe I missed something in the docs, but a method like Exporter's `export_to_level()` seems to be not available. Or is there any other way for a module that is an `Exporter::Tiny` to have it's own `import()` method and delegate to `Exporter::Tiny->import` (somehow)  from there?

Sorry if this is not an issue but comes from my ignorance.

**Comment by tobyink** [comment]
Generally the easiest way to do this is something like:

```
package My::Thing;
use parent 'Exporter::Tiny';
sub import {
  my ($me, @args) = @_;
  # do stuff here
  # maybe adjust @args
  @_ = ($me, @args);
  goto \&Exporter::Tiny::import;
}
```

Though overriding one of the `_exporter_*` methods might be a better idea, depending on exactly what you want to achieve.

**Comment by jo-37** [comment]
Thanks! This is exactly what I was looking for. Overriding `_exporter_*` methods is not an option if `Exporter::Tiny` and `Filter::Simple` shall be used together.

**Comment by tobyink** [comment]
Filter::Simple will stomp on any `import` method you write yourself.

Honestly, I think the best solution for this would be to do:

```perl
## lib/My/Thing.pm
use v5.12;
use strict;
use warnings;

package My::Thing {
  use Import::Into;
  sub filter_package   { __PACKAGE__ . "::_Filter"   }
  sub exporter_package { __PACKAGE__ . "::_Exporter" }
  sub import {
    my $me  = shift;
    my $you = caller;
    $me->filter_package->import::into($you);
    $me->exporter_package->import::into($you, @_);
  }
}

package My::Thing::_Filter {
  use Filter::Simple;
  ...; # filtering stuff
}

package My::Thing::_Exporter {
  use parent 'Exporter::Tiny';
  ...; # exporting stuff
}
```

**Comment by jo-37** [comment]
This approach is very clean, indeed. However, `Filter::Simple` can cope with modules that are an `Exporter` as well as ones that have their own `import` method. So all it needs for a friendly coexistence of `Filter::Simple` and `Exporter::Tiny` is this minimalist sub in the module:
```
sub import {
    goto \&Export::Tiny::import;
}
```
Thanks again for your assistance!

**Comment by tobyink** [comment]
Hmm, in that case, you might be able to reduce it to:

```
BEGIN { *import = \&Exporter::Tiny::import };
```

**Comment by jo-37** [comment]
It works!
That's why I like Perl so much.
