### ISSUE TITLE
Questions about regular expressions

### ISSUE THREAD

**Issue by bokutin** [tobyink/p5-exporter-tiny#6]
https://github.com/tobyink/p5-exporter-tiny/blob/0c5cb5fb9c9b421b4f5f18b623ecc988a8c71e9c/lib/Exporter/Tiny.pm#L33

Is modifier required for regular expressions?

$name =~ m{\A/.+/[msixpodual]+\z}
or
$name =~ m{\A/.+/[msixpodual]*\z}

**Comment by tobyink** [comment]
Hmm, I think you're right. It should be a `*`

**Comment by tobyink** [comment]
Pushed a change to github. I'll release new version assuming it passes all checks on Travis.

**Comment by tobyink** [comment]
Looks good. I'll release a fix today, hopefully.

**Comment by tobyink** [comment]
Released https://metacpan.org/release/TOBYINK/Exporter-Tiny-1.002002

**Comment by bokutin** [comment]
Thank you for your quick response!
